const constants = {
  SEARCH_DEVICES: 'SEARCH_DEVICES',
  FETCH_DEVICES: 'FETCH_DEVICES',

  ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
  ADD_DEVICE_ERROR: 'ADD_DEVICE_ERROR',
  ADD_DEVICE: 'ADD_DEVICE',
  TOGGLE_MODAL: 'TOGGLE_MODAL'
}

export default constants
